project:
  type: website
  resources:
    - CNAME

website:
  title: "ORION-DBs"
  site-url: "https://orion-dbs.community"
  favicon: favicon.ico
  navbar:
    left:
      - text: Collections
        menu:
          - text: Overview
            href: collections/
          - text: CWTS Leiden Datasets
            href: collections/cwts/
          - text: InSySPo Campinas Datasets
            href: collections/insyspo/
          - text: MultiObs Campinas Datasets
            href: collections/multiobs/
          - text: Sesame Open Science Datasets
            href: collections/sos/
          - text: SUB GÃ¶ttingen Datasets
            href: collections/subugoe/
      - text: News & Tutorials
        href: blog/
    right:
      - href: about.qmd
        text: About
      - text: Contribute
        href: contributing.qmd
      - icon: rss
        href: blog/index.xml
      - icon: github
        href: https://github.com/orion-dbs-community/website
  page-footer:
    left:
      - text: "The content on this website is licensed under <a href='https://creativecommons.org/publicdomain/zero/1.0/'>CC0</a>."
    center:
      - text: "Privacy"
        href: privacy.qmd
      - text: "Contact"
        href: contact.qmd
    right:
      - text: "Built with <a href='https://quarto.org/'>Quarto</a>"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mainfont: system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif
