project:
  type: website

website:
  title: "GBQ-ORI"
  navbar:
    left:
      - text: Projects
        menu:
          - text: InSySPo Campinas Datasets
            href: projects/insyspo/
          - text: Sesame Open Datasets
            href: projects/sos/
          - text: SUB GÃ¶ttingen Datasets
            href: projects/subugoe/
    right:
      - href: about.qmd
        text: About
      - text: Contribute
        href: contributing.qmd
      - icon: github
        href: https://github.com/njahn82/bqori_website
  page-footer:
    left:
      - text: "The content on this website is licensed under <a href='https://creativecommons.org/publicdomain/zero/1.0/'>CC0</a>."
    right:
      - text: "Website build with <a href='https://quarto.org/'>Quarto.</a>"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



