project:
  type: website

website:
  title: "GBQ-ORI"
  navbar:
    left:
      - text: Projects
        menu:
          - text: InSySPo Campinas Datasets
            href: projects/insyspo/
          - text: Sesame Open Datasets
            href: projects/sos/
          - text: SUB GÃ¶ttingen Datasets
            href: projects/subugoe/
    right:
      - href: about.qmd
        text: About
      - text: Contribute
        href: contributing.qmd
      - icon: github
        href: https://github.com/njahn82/bqori_website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



