project:
  type: website

website:
  title: "ORI-BQ"
  site-url: "https://effulgent-pika-584bcf.netlify.app/"
  navbar:
    left:
      - text: Projects
        menu:
          - text: InSySPo Campinas Datasets
            href: projects/insyspo/
          - text: Sesame Open Datasets
            href: projects/sos/
          - text: SUB GÃ¶ttingen Datasets
            href: projects/subugoe/
      - text: News & Tutorials
        href: blog/
    right:
      - href: about.qmd
        text: About
      - text: Contribute
        href: contributing.qmd
      - icon: rss
        href: blog/index.xml
      - icon: github
        href: https://github.com/njahn82/bqori_website
  page-footer:
    left:
      - text: "The content on this website is licensed under <a href='https://creativecommons.org/publicdomain/zero/1.0/'>CC0</a>."
    center:
      - text: "Privacy"
        href: privacy.qmd
    right:
      - text: "Website build with <a href='https://quarto.org/'>Quarto.</a>"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mainfont: system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif



